[workspace]
members = [
    "pefbin","pefapi"
] 
default-members = ["pefbin"]
[workspace.package]
version = "0.0.2"
edition = "2021"
authors = ["yum <yumzi114@gmail.com>"]
readme = "README.md"
license = "MIT OR Apache-2.0"